### PR TITLE
Remove text about companion videos

### PR DESCRIPTION
**Pull request by psteeve**
Hi, 

I think we can remove this sentence about the companion videos because it's difficult to know where to find it and it's in french which can be a problem for some users.

Thanks.

### CODE REVIEW

**Comment by Ducasse** [comment]
you see this video is both in english and french and it has subtitles in Japanese, frnech, english, spanish. So I would let it.

**Comment by Ducasse** [comment]
I wrote 

Note that the development flow promoted by this little tutorial is ''traditional'' in the sense that you will define a package, a class, ''then'' define its instance variable ''then'' define its methods ''and'' finally execute it (See the companion video below). Now in Pharo, developers often follow a ''totally'' different style (that we call live coding) where they execute an expression that raises errors and they code in the debugger and let the system define some instance variables and methods on the fly for them. Once you will have finished this tutorial, you will feel more confident with Pharo and we strongly suggest you to try the other style (See the second video showing such different development practices).

!!!! Companion videos
You can find at *http://mooc.pharo.org/*, the mooc videos with french and english voice over and subtitles in different languages (japanese, spanish, french, english).
Among such videos, two videos are related to the counter exercises. They are called "Redo" because this is left to the reader to follow and redo the 
videos. 
- Coding the traditional way: *http://rmod-pharo-mooc.lille.inria.fr/MOOC/Videos/W1/*
- Coding in the debugger: *http://rmod-pharo-mooc.lille.inria.fr/MOOC/Videos/W2/*

**Comment by Ducasse** [comment]
I committed a new version so I will close this issue. 
Thanks for raising the problem

**Comment by psteeve** [comment]
Ok fine.

Thank you.

**Pull request closed without merging**
