### PR TITLE
Update Introduction.pillar

### PR DESCRIPTION
**Pull request by terrpy**
I really want to help the Pharo project. I have programmed for years, but I am new to Pharo and SmallTalk. I am a native English speaker, so I can help with the English grammar in this book, while learning Pharo at the same time.

Thanks for this great book!

Terry

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Thank you for your contribution Terry.

**Comment by Ducasse** [comment]
Thanks a lot Terry. I would love to be a native english speaker. And yes you can have a great impact and be of a great help for Pharo.

**Comment by Ducasse** [comment]
Terry can you add yourselves in the list of people that I thank? :)

**Comment by terrpy** [comment]
Yes, @Ducasse, I will try to add my name and keep working.

**Pull request merged**
